"""create disasters table

Revision ID: 2a6c11d0648c
Revises: 588ff0f50742
Create Date: 2026-08-28 23:01:42.128133

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '2a6c11d0648c'
down_revision: Union[str, Sequence[str], None] = '588ff0f50742'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('disasters',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('description', sa.String(length=5000), nullable=False),
    sa.Column('disaster_type', sa.String(length=30), nullable=False),
    sa.Column('severity', sa.String(length=20), nullable=False),
    sa.Column('status', sa.String(length=20), server_default=sa.text("'DRAFT'"), nullable=False),
    sa.Column('latitude', sa.Float(), nullable=False),
    sa.Column('longitude', sa.Float(), nullable=False),
    sa.Column('location', sa.String(length=500), nullable=True),
    sa.Column('created_by_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.CheckConstraint('latitude >= -90 AND latitude <= 90', name='ck_disasters_latitude'),
    sa.CheckConstraint('longitude >= -180 AND longitude <= 180', name='ck_disasters_longitude'),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_disasters_created_by_id', 'disasters', ['created_by_id'], unique=False)
    op.create_index('ix_disasters_status', 'disasters', ['status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_disasters_status', table_name='disasters')
    op.drop_index('ix_disasters_created_by_id', table_name='disasters')
    op.drop_table('disasters')
    # ### end Alembic commands ###
