"""create incidents table

Revision ID: 588ff0f50742
Revises: 4fb3b2eef59b
Create Date: 2026-08-28 22:22:47.672032

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '588ff0f50742'
down_revision: Union[str, Sequence[str], None] = '4fb3b2eef59b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('incidents',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('description', sa.String(length=5000), nullable=False),
    sa.Column('incident_type', sa.String(length=30), nullable=False),
    sa.Column('severity', sa.String(length=20), nullable=False),
    sa.Column('status', sa.String(length=20), server_default=sa.text("'OPEN'"), nullable=False),
    sa.Column('latitude', sa.Float(), nullable=False),
    sa.Column('longitude', sa.Float(), nullable=False),
    sa.Column('location', sa.String(length=500), nullable=True),
    sa.Column('created_by_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.CheckConstraint('latitude >= -90 AND latitude <= 90', name='ck_incidents_latitude'),
    sa.CheckConstraint('longitude >= -180 AND longitude <= 180', name='ck_incidents_longitude'),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_incidents_created_by_id', 'incidents', ['created_by_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_incidents_created_by_id', table_name='incidents')
    op.drop_table('incidents')
    # ### end Alembic commands ###
